Repository readmeio/fetch-har, pull requests merged in 2023-09, with the labels that each got.

#421 feat: dropping support for node 16
  .eslintrc
  .github/dependabot.yml
  .github/workflows/ci.yml
  README.md
  example.js
  package-lock.json
  package.json
  src/index.ts
  test/.eslintrc
  test/browser-quirks.test.ts
  test/file-upload-quirks.test.ts
  test/index.test.ts
  test/mocking/fetch-mock.test.ts
  test/mocking/nock.test.ts
  test/node-quirks.test.ts
Labels: enhancement

#428 test: add `msw` tests
  README.md
  package-lock.json
  package.json
  test/mocking/msw.test.ts
Labels: enhancement

#429 refactor: remove `readable-stream` polyfill
  package-lock.json
  package.json
  src/index.ts
Labels: dependencies, refactor

#427 feat: esm and cjs exports
  .eslintrc
  .github/dependabot.yml
  .github/workflows/ci.yml
  .github/workflows/codeql-analysis.yml
  README.md
  example.cjs
  example.mjs
  package-lock.json
  package.json
  src/index.ts
  src/types.ts
  test/file-upload-quirks.test.ts
  test/mocking/msw.test.ts
  tsconfig.json
  tsup.config.ts
Labels: enhancement

#431 fix: convert library to module
  .eslintrc
  example.mjs
  package.json
  src/index.ts
  test/browser-quirks.test.ts
  test/file-upload-quirks.test.ts
  test/index.test.ts
  test/mocking/fetch-mock.test.ts
  test/mocking/msw.test.ts
  test/node-quirks.test.ts
Labels: bug, refactor
